name: backend
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        
jobs:
    b_p_backend:
      runs-on: self-hosted
      steps:
        - 
         name: Checkout MB
         uses: actions/checkout@v3
         with:
          repository: Radklif/backend_test
          ref: ${{ inputs.branch }}   # dev или master ветка
          token: ${{ secrets.morfis_build_pat }}
          path: morfis_backend
        -
         name: Set up QEMU
         uses: docker/setup-qemu-action@v2
        -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
        -
         name: Docker login
         uses: docker/login-action@v2
         with:
          registry: localhost:5000
          username: test
          password: test
        -
         name: Build and push
         uses: docker/build-push-action@v3
         with:
          context: ./test_backend
          file: ./test_backend/Dockerfile
          push: true
          tags: localhost:5000/test_backend
