name: backend
on:
  workflow_dispatch:
        
jobs:
    b_p_backend:
      env:
        REGISTRY: hub.morfis.ru
        IMAGE: hub.morfis.ru/test_backend
      runs-on: self-hosted
      steps:
        - 
         name: Checkout TB
         uses: actions/checkout@v3
        -
         name: Set up QEMU
         uses: docker/setup-qemu-action@v2
        -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
        -
         name: Docker login
         uses: docker/login-action@v2
         with:
          registry: hub.morfis.ru
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
         name: Build and push
         uses: docker/build-push-action@v3
         with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
